### ISSUE TITLE
Migrate to GitHub container registry

### ISSUE THREAD

**Issue by kinnarr** [metricq/metricq#80]
Docker registry is becoming very expensive.

See https://blog.alexellis.io/docker-is-deleting-open-source-images/

TODO:

- [x] metricq/metricq-python#158
- [x] metricq/metricq-sink-websocket#15
- [x] metricq/metricq-wizard-backend#44
- [x] metricq/metricq-grafana#54
- [x] metricq/metricq-source-rabbitmq#6
- [x] metricq/metricq-manager#48
- [x] metricq/metricq-webview#189
- [x] metricq/metricq-explorer-frontend#4
- [x] metricq/metricq-sink-nsca#72
- [x] metricq/metricq-source-snmp#14
- [x] metricq/metricq-source-http#9
- [x] metricq/metricq-combinator#14
- [x] metricq/metricq-source-sysinfo#13
- [x] metricq/metricq-source-ipmi#22
